import type { Section } from "../store/types";

/**
 * Maps normalized (lowercase) item names to section names.
 * Section names match DEFAULT_SECTIONS names (case-insensitive lookup at runtime).
 * Includes English and German names for common grocery items.
 */
const ITEM_SECTION_MAP: Record<string, string> = {
  // ── Produce ──────────────────────────────────────────────────────────────
  apple: "produce",
  apfel: "produce",
  äpfel: "produce",
  apricot: "produce",
  aprikose: "produce",
  artichoke: "produce",
  artischocke: "produce",
  arugula: "produce",
  rucola: "produce",
  asparagus: "produce",
  spargel: "produce",
  avocado: "produce",
  banana: "produce",
  banane: "produce",
  basil: "produce",
  basilikum: "produce",
  beet: "produce",
  "rote bete": "produce",
  "rote beete": "produce",
  blueberry: "produce",
  heidelbeere: "produce",
  blaubeere: "produce",
  broccoli: "produce",
  brokkoli: "produce",
  "brussels sprouts": "produce",
  rosenkohl: "produce",
  cabbage: "produce",
  kohl: "produce",
  weißkohl: "produce",
  carrot: "produce",
  karotte: "produce",
  möhre: "produce",
  cauliflower: "produce",
  blumenkohl: "produce",
  celery: "produce",
  sellerie: "produce",
  cherry: "produce",
  kirsche: "produce",
  "cherry tomatoes": "produce",
  kirschtomaten: "produce",
  cilantro: "produce",
  koriander: "produce",
  corn: "produce",
  mais: "produce",
  cucumber: "produce",
  gurke: "produce",
  dill: "produce",
  eggplant: "produce",
  aubergine: "produce",
  fennel: "produce",
  fenchel: "produce",
  fig: "produce",
  feige: "produce",
  garlic: "produce",
  knoblauch: "produce",
  ginger: "produce",
  ingwer: "produce",
  grapes: "produce",
  grape: "produce",
  traube: "produce",
  weintraube: "produce",
  "green beans": "produce",
  "grüne bohnen": "produce",
  "green onion": "produce",
  frühlingszwiebel: "produce",
  lauchzwiebel: "produce",
  herbs: "produce",
  kräuter: "produce",
  kale: "produce",
  grünkohl: "produce",
  kiwi: "produce",
  leek: "produce",
  lauch: "produce",
  porree: "produce",
  lemon: "produce",
  zitrone: "produce",
  lettuce: "produce",
  salat: "produce",
  kopfsalat: "produce",
  lime: "produce",
  limette: "produce",
  mango: "produce",
  melon: "produce",
  melone: "produce",
  mint: "produce",
  minze: "produce",
  mushroom: "produce",
  champignon: "produce",
  pilze: "produce",
  pilz: "produce",
  nectarine: "produce",
  nektarine: "produce",
  onion: "produce",
  zwiebel: "produce",
  orange: "produce",
  parsley: "produce",
  petersilie: "produce",
  parsnip: "produce",
  pastinake: "produce",
  peach: "produce",
  pfirsich: "produce",
  pear: "produce",
  birne: "produce",
  peas: "produce",
  erbsen: "produce",
  pepper: "produce",
  paprika: "produce",
  pineapple: "produce",
  ananas: "produce",
  plum: "produce",
  pflaume: "produce",
  pomegranate: "produce",
  granatapfel: "produce",
  potato: "produce",
  kartoffel: "produce",
  kartoffeln: "produce",
  pumpkin: "produce",
  kürbis: "produce",
  radish: "produce",
  radieschen: "produce",
  raspberry: "produce",
  himbeere: "produce",
  rosemary: "produce",
  rosmarin: "produce",
  spinach: "produce",
  spinat: "produce",
  "spring onion": "produce",
  strawberry: "produce",
  erdbeere: "produce",
  "sweet potato": "produce",
  süßkartoffel: "produce",
  thyme: "produce",
  thymian: "produce",
  tomato: "produce",
  tomate: "produce",
  watermelon: "produce",
  wassermelone: "produce",
  zucchini: "produce",

  // ── Bakery ────────────────────────────────────────────────────────────────
  bagel: "bakery",
  baguette: "bakery",
  bread: "bakery",
  brot: "bakery",
  brioche: "bakery",
  brötchen: "bakery",
  roll: "bakery",
  rolls: "bakery",
  cake: "bakery",
  kuchen: "bakery",
  ciabatta: "bakery",
  croissant: "bakery",
  muffin: "bakery",
  pita: "bakery",
  pretzel: "bakery",
  brezel: "bakery",
  sourdough: "bakery",
  sauerteig: "bakery",
  toast: "bakery",
  toastbrot: "bakery",
  tortilla: "bakery",

  // ── Meat & Fish ──────────────────────────────────────────────────────────
  bacon: "meat & fish",
  speck: "meat & fish",
  beef: "meat & fish",
  rind: "meat & fish",
  rindfleisch: "meat & fish",
  chicken: "meat & fish",
  hähnchen: "meat & fish",
  hühnchen: "meat & fish",
  huhn: "meat & fish",
  cod: "meat & fish",
  kabeljau: "meat & fish",
  crab: "meat & fish",
  krabbe: "meat & fish",
  duck: "meat & fish",
  ente: "meat & fish",
  fish: "meat & fish",
  fisch: "meat & fish",
  ham: "meat & fish",
  schinken: "meat & fish",
  herring: "meat & fish",
  hering: "meat & fish",
  lamb: "meat & fish",
  lamm: "meat & fish",
  lammfleisch: "meat & fish",
  mince: "meat & fish",
  hackfleisch: "meat & fish",
  "ground beef": "meat & fish",
  pork: "meat & fish",
  schwein: "meat & fish",
  schweinefleisch: "meat & fish",
  salmon: "meat & fish",
  lachs: "meat & fish",
  salami: "meat & fish",
  sausage: "meat & fish",
  wurst: "meat & fish",
  bratwurst: "meat & fish",
  shrimp: "meat & fish",
  garnele: "meat & fish",
  garnelen: "meat & fish",
  steak: "meat & fish",
  tilapia: "meat & fish",
  trout: "meat & fish",
  forelle: "meat & fish",
  tuna: "meat & fish",
  thunfisch: "meat & fish",
  turkey: "meat & fish",
  truthahn: "meat & fish",
  pute: "meat & fish",
  veal: "meat & fish",
  kalbfleisch: "meat & fish",

  // ── Dairy & Eggs ─────────────────────────────────────────────────────────
  butter: "dairy & eggs",
  cheddar: "dairy & eggs",
  cheese: "dairy & eggs",
  käse: "dairy & eggs",
  "cottage cheese": "dairy & eggs",
  hüttenkäse: "dairy & eggs",
  cream: "dairy & eggs",
  sahne: "dairy & eggs",
  "cream cheese": "dairy & eggs",
  frischkäse: "dairy & eggs",
  egg: "dairy & eggs",
  eggs: "dairy & eggs",
  ei: "dairy & eggs",
  eier: "dairy & eggs",
  feta: "dairy & eggs",
  gouda: "dairy & eggs",
  kefir: "dairy & eggs",
  milk: "dairy & eggs",
  milch: "dairy & eggs",
  mozzarella: "dairy & eggs",
  "oat milk": "dairy & eggs",
  hafermilch: "dairy & eggs",
  parmesan: "dairy & eggs",
  quark: "dairy & eggs",
  "sour cream": "dairy & eggs",
  schmand: "dairy & eggs",
  sauerrahm: "dairy & eggs",
  "soy milk": "dairy & eggs",
  sojamilch: "dairy & eggs",
  "whipped cream": "dairy & eggs",
  schlagsahne: "dairy & eggs",
  yogurt: "dairy & eggs",
  joghurt: "dairy & eggs",
  "almond milk": "dairy & eggs",
  mandelmilch: "dairy & eggs",

  // ── Frozen ───────────────────────────────────────────────────────────────
  edamame: "frozen",
  "fish sticks": "frozen",
  fischstäbchen: "frozen",
  "frozen fries": "frozen",
  pommes: "frozen",
  "frozen peas": "frozen",
  "frozen pizza": "frozen",
  tiefkühlpizza: "frozen",
  "frozen vegetables": "frozen",
  tiefkühlgemüse: "frozen",
  "ice cream": "frozen",
  eis: "frozen",
  speiseeis: "frozen",
  waffles: "frozen",
  waffeln: "frozen",

  // ── Beverages ─────────────────────────────────────────────────────────────
  beer: "beverages",
  bier: "beverages",
  "coconut water": "beverages",
  coffee: "beverages",
  kaffee: "beverages",
  "energy drink": "beverages",
  juice: "beverages",
  saft: "beverages",
  orangensaft: "beverages",
  apfelsaft: "beverages",
  lemonade: "beverages",
  limonade: "beverages",
  soda: "beverages",
  "sparkling water": "beverages",
  sprudelwasser: "beverages",
  mineralwasser: "beverages",
  tea: "beverages",
  tee: "beverages",
  water: "beverages",
  wasser: "beverages",
  wine: "beverages",
  wein: "beverages",
  rotwein: "beverages",
  weißwein: "beverages",

  // ── Pantry ────────────────────────────────────────────────────────────────
  "baking powder": "pantry",
  backpulver: "pantry",
  "baking soda": "pantry",
  natron: "pantry",
  "black pepper": "pantry",
  pfeffer: "pantry",
  "bread crumbs": "pantry",
  paniermehl: "pantry",
  semmelbrösel: "pantry",
  broth: "pantry",
  brühe: "pantry",
  "canned beans": "pantry",
  bohnen: "pantry",
  "canned tomatoes": "pantry",
  dosentomaten: "pantry",
  "passierte tomaten": "pantry",
  capers: "pantry",
  kapern: "pantry",
  cereal: "pantry",
  müsli: "pantry",
  "cocoa powder": "pantry",
  kakaopulver: "pantry",
  "coconut milk": "pantry",
  kokosmilch: "pantry",
  cornstarch: "pantry",
  speisestärke: "pantry",
  couscous: "pantry",
  curry: "pantry",
  flour: "pantry",
  mehl: "pantry",
  honey: "pantry",
  honig: "pantry",
  jam: "pantry",
  marmelade: "pantry",
  ketchup: "pantry",
  lentils: "pantry",
  linsen: "pantry",
  maple: "pantry",
  mayonnaise: "pantry",
  mayo: "pantry",
  mustard: "pantry",
  senf: "pantry",
  nutella: "pantry",
  oats: "pantry",
  haferflocken: "pantry",
  "olive oil": "pantry",
  olivenöl: "pantry",
  "vegetable oil": "pantry",
  öl: "pantry",
  paprikapulver: "pantry",
  pasta: "pantry",
  nudeln: "pantry",
  spaghetti: "pantry",
  penne: "pantry",
  "peanut butter": "pantry",
  erdnussbutter: "pantry",
  rice: "pantry",
  reis: "pantry",
  salt: "pantry",
  salz: "pantry",
  "soy sauce": "pantry",
  sojasoße: "pantry",
  sojasosse: "pantry",
  stock: "pantry",
  sugar: "pantry",
  zucker: "pantry",
  "tomato paste": "pantry",
  tomatenmark: "pantry",
  "vanilla extract": "pantry",
  vanille: "pantry",
  vinegar: "pantry",
  essig: "pantry",
  yeast: "pantry",
  hefe: "pantry",

  // ── Snacks ────────────────────────────────────────────────────────────────
  candy: "snacks",
  süßigkeiten: "snacks",
  chips: "snacks",
  chocolate: "snacks",
  schokolade: "snacks",
  cookies: "snacks",
  kekse: "snacks",
  crackers: "snacks",
  "granola bar": "snacks",
  müsliriegel: "snacks",
  riegel: "snacks",
  "gummy bears": "snacks",
  gummibärchen: "snacks",
  haribo: "snacks",
  nuts: "snacks",
  nüsse: "snacks",
  mandeln: "snacks",
  cashews: "snacks",
  popcorn: "snacks",
  pretzels: "snacks",
  brezeln: "snacks",
  raisins: "snacks",
  rosinen: "snacks",

  // ── Household ─────────────────────────────────────────────────────────────
  "aluminum foil": "household",
  alufolie: "household",
  "baking paper": "household",
  backpapier: "household",
  "cleaning spray": "household",
  reiniger: "household",
  allzweckreiniger: "household",
  "dish soap": "household",
  spülmittel: "household",
  "dishwasher tabs": "household",
  spülmaschinentabs: "household",
  "fabric softener": "household",
  weichspüler: "household",
  "garbage bags": "household",
  müllbeutel: "household",
  müllsäcke: "household",
  "kitchen roll": "household",
  küchenrolle: "household",
  "laundry detergent": "household",
  waschmittel: "household",
  "paper towels": "household",
  küchenpapier: "household",
  "plastic wrap": "household",
  frischhaltefolie: "household",
  sponge: "household",
  schwamm: "household",
  spülschwamm: "household",
  "toilet paper": "household",
  toilettenpapier: "household",
  klopapier: "household",
  "zip bags": "household",
  gefrierbeutel: "household",

  // ── Personal Care ─────────────────────────────────────────────────────────
  conditioner: "personal care",
  pflegespülung: "personal care",
  deodorant: "personal care",
  deo: "personal care",
  lotion: "personal care",
  moisturizer: "personal care",
  feuchtigkeitscreme: "personal care",
  razor: "personal care",
  rasierer: "personal care",
  shampoo: "personal care",
  soap: "personal care",
  seife: "personal care",
  "sun cream": "personal care",
  sonnencreme: "personal care",
  sunscreen: "personal care",
  toothbrush: "personal care",
  zahnbürste: "personal care",
  toothpaste: "personal care",
  zahnpasta: "personal care",
  zahncreme: "personal care",
};

/**
 * Given an item name and the user's current sections, returns the section ID
 * that best matches the item — or undefined if no match found.
 *
 * Matching order:
 * 1. Exact match on the full normalized name
 * 2. Dictionary key that is contained within the input (e.g. "bio banane" → "banane")
 * 3. Input contained within a dictionary key (e.g. "banan" → "banana") — substring prefix match
 */
export function getSuggestedSectionId(
  itemName: string,
  sections: Section[],
): string | undefined {
  const normalized = itemName.toLowerCase().trim();
  if (!normalized) return undefined;

  // 1. Exact match
  let sectionName = ITEM_SECTION_MAP[normalized];

  // 2. A known key is a word-boundary substring of the input
  if (!sectionName) {
    for (const key of Object.keys(ITEM_SECTION_MAP)) {
      if (normalized.includes(key)) {
        sectionName = ITEM_SECTION_MAP[key];
        break;
      }
    }
  }

  // 3. The input is a prefix of a known key (min 3 chars to avoid false positives)
  if (!sectionName && normalized.length >= 3) {
    for (const key of Object.keys(ITEM_SECTION_MAP)) {
      if (key.startsWith(normalized)) {
        sectionName = ITEM_SECTION_MAP[key];
        break;
      }
    }
  }

  if (!sectionName) return undefined;

  const match = sections.find((s) => s.name.toLowerCase() === sectionName);
  return match?.id;
}
